version: "3.7"

networks:
    mysql-service:

services: 
    mysql: 
        container_name: mysql57
        image: mysql:5.7
        restart: always
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
        volumes: 
            - ./conf:/etc/mysql
            - ./logs:/var/log/mysql
            - ./data:/var/lib/mysql
        ports: 
            - 3306:3306